---
name: 'Powerpipe'
on:
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  powerpipe:
    uses: clouddrove/github-shared-workflows/.github/workflows/powerpipe.yml@feat/powerpipe
    with:
      cloud_provider: 'AWS'
      mod_url: "https://github.com/turbot/steampipe-mod-terraform-aws-compliance"
      plugin_connection: |
        connection "aws_tf" {
          plugin = "terraform"
          configuration_file_paths = [
            "terraform/aws/**/*.tf"
          ]
        }
        connection "aws" {
          plugin = "aws"
        }
      benchmarks: |
        ec2
    secrets: 
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      aws_assume_role: ${{ secrets.assume_role }}
...
